<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Build tool: regenerate the Moodle-XML question import file from the truth_table
 * preset catalogue. Run with the php CLI (no Moodle bootstrap needed).
 *
 * The generated file (qtype/graphitoubb/db/preset_questions.xml) is shipped with the
 * qtype so teachers can import it into the Question Bank, and is also imported
 * automatically on install/upgrade by qtype_graphitoubb's seeder.
 *
 * Usage:  php local/graphitoubb/cli/export_questions_xml.php
 *
 * @package    local_graphitoubb
 * @copyright  2026 GraphitoUBB
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

spl_autoload_register(static function (string $class): void {
    $prefix = 'local_graphitoubb\\';
    if (strpos($class, $prefix) !== 0) {
        return;
    }
    $rel  = substr($class, strlen($prefix));
    $path = __DIR__ . '/../classes/' . str_replace('\\', '/', $rel) . '.php';
    if (is_readable($path)) {
        require $path;
    }
});

use local_graphitoubb\catalog\preset_catalog;
use local_graphitoubb\tools\truth_table\domain\serializer;

$catalogdir = __DIR__ . '/../catalog';

// The qtype lives at qtype/graphitoubb in the repo but is mounted at
// question/type/graphitoubb inside a Moodle install. Write to whichever db/ dir exists.
$candidates = [
    __DIR__ . '/../../../question/type/graphitoubb/db',
    __DIR__ . '/../../../qtype/graphitoubb/db',
];
$outdir = null;
foreach ($candidates as $c) {
    if (is_dir($c)) {
        $outdir = $c;
        break;
    }
}
if ($outdir === null) {
    fwrite(STDERR, "Could not locate the qtype db/ directory.\n");
    exit(1);
}
$outfile = $outdir . '/preset_questions.xml';
$categoryname = 'GraphitoUBB — Tablas de verdad (pre-instaladas)';
$categoryinfo = 'Ejercicios de tabla de verdad listos para usar, instalados con el plugin qtype_graphitoubb.';

$ser     = new serializer();
$catalog = new preset_catalog($catalogdir);
// truth_table + the graph/tree tools (grafo, arbol) all ship as "preguntas tipo".
$presets = array_merge(
    $catalog->all('truth_table'),
    $catalog->all('grafo'),
    $catalog->all('arbol')
);

/**
 * Escape text for an XML element (not CDATA).
 */
$esc = static fn(string $s): string => htmlspecialchars($s, ENT_QUOTES | ENT_XML1, 'UTF-8');

/**
 * Build the scoring_config JSON the qtype stores separately, per exercise type.
 */
$scoringfor = static function (array $payload): string {
    if (($payload['type'] ?? '') === 'complete') {
        return '{}';
    }
    $s = $payload['scoring'] ?? ['radio_weight' => 50, 'table_weight' => 50, 'wrong_radio_policy' => 'strict'];
    return json_encode($s, JSON_UNESCAPED_UNICODE);
};

$lines   = [];
$lines[] = '<?xml version="1.0" encoding="UTF-8"?>';
$lines[] = '<!-- Auto-generated by local/graphitoubb/cli/export_questions_xml.php — do not edit by hand. -->';
$lines[] = '<quiz>';

// Category marker so the import lands in a dedicated category.
$lines[] = '  <question type="category">';
$lines[] = '    <category><text>$course$/' . $esc($categoryname) . '</text></category>';
$lines[] = '    <info format="html"><text>' . $esc($categoryinfo) . '</text></info>';
$lines[] = '  </question>';

$uijson = json_encode(['intermediate_subformulas' => 'auto', 'row_order' => 'canonical'], JSON_UNESCAPED_UNICODE);

foreach ($presets as $p) {
    $payload = $p->payload;
    // truth_table uses the canonical serializer; grafo/arbol store the payload
    // JSON verbatim (the qtype import recomputes the hash for them).
    if ($p->tool === 'truth_table') {
        $payloadjson = $ser->encode($payload);
        $hash        = $ser->hash($payload);
        $scoringjson = $scoringfor($payload);
    } else {
        $payloadjson = json_encode($payload, JSON_UNESCAPED_UNICODE);
        $hash        = hash('sha256', $payloadjson);
        $scoringjson = '{}';
    }

    $lines[] = '  <question type="graphitoubb">';
    $lines[] = '    <name><text>' . $esc($p->title) . '</text></name>';
    $lines[] = '    <questiontext format="html"><text><![CDATA[<p>' . $p->summary . '</p>]]></text></questiontext>';
    $lines[] = '    <generalfeedback format="html"><text></text></generalfeedback>';
    $lines[] = '    <defaultgrade>1.0000000</defaultgrade>';
    $lines[] = '    <penalty>0.0000000</penalty>';
    $lines[] = '    <hidden>0</hidden>';
    $lines[] = '    <idnumber>' . $esc($p->key) . '</idnumber>';
    $lines[] = '    <tool>' . $esc($p->tool) . '</tool>';
    $lines[] = '    <exercise_type>' . $esc($p->type) . '</exercise_type>';
    $lines[] = '    <schema_version>1</schema_version>';
    $lines[] = '    <problem_payload><![CDATA[' . $payloadjson . ']]></problem_payload>';
    $lines[] = '    <scoring_config><![CDATA[' . $scoringjson . ']]></scoring_config>';
    $lines[] = '    <ui_config><![CDATA[' . $uijson . ']]></ui_config>';
    $lines[] = '    <payload_hash>' . $esc($hash) . '</payload_hash>';
    $lines[] = '  </question>';
}

$lines[] = '</quiz>';
$lines[] = '';

$xml = implode("\n", $lines);
file_put_contents($outfile, $xml);

echo 'Wrote ' . count($presets) . " questions to:\n  " . realpath($outfile) . "\n";
